### ISSUE TITLE
Can I separate the function and use it for all colors, instead of repeating it for every color?

### ISSUE THREAD

**Issue by saadeghi** [adamwathan/tailwind-css-variable-text-opacity-demo#1]
If I add ~100 colors in this format, this repetitive function doesn't look good
```js
module.exports = {
  theme: {
    colors: {
      primary: ({ opacityVariable, opacityValue }) => {
        if (opacityValue !== undefined) {
          return `rgba(var(--color-primary), ${opacityValue})`
        }
        if (opacityVariable !== undefined) {
          return `rgba(var(--color-primary), var(${opacityVariable}, 1))`
        }
        return `rgb(var(--color-primary))`
      },
      secondary: ({ opacityVariable, opacityValue }) => {
        if (opacityValue !== undefined) {
          return `rgba(var(--color-secondary), ${opacityValue})`
        }
        if (opacityVariable !== undefined) {
          return `rgba(var(--color-secondary), var(${opacityVariable}, 1))`
        }
        return `rgb(var(--color-secondary))`
      },
    },
  },
}
```
So I decided to use a single function for all colors
```js
colorFunction = (params) => {
  if (params.opacityValue !== undefined) {
    return `rgba(var(--color-primary), ${params.opacityValue})`
  }
  if (params.opacityVariable !== undefined) {
    return `rgba(var(--color-primary), var(${params.opacityVariable}, 1))`
  }
  return `rgb(var(--color-primary))`
}

module.exports = {
  theme: {
    extend: {
      colors: {
        "primary": colorFunction({ opacityVariable, opacityValue }),
      }
    }
  }
}
```
but as soon as I do this, I get `opacityVariable is not defined` error.  
I'm not sure if I'm doing it wrong or not but I don't know why `opacityVariable` doesn't throw an error when the function is inside the `colors` object.  

Can someone point what am I doing wrong?

**Comment by tablufc88** [comment]
Same issue here.

**Comment by KevinAst** [comment]
You are executing your `colorFunction()` at structure build-time, **NOT** at application run-time.

In addition, your `colorFunction()` needs to parameterize the `cssVar` in use.  You don't want to use the same `color-primary` cssVar in every case.

Try these revisions ...

**UPDATE**: In answering your question I found one of my problems.  The code below has **now been tested and does work**!

The prior version of my code snippet was **not** accepting the paramaeters because I had renamed them **FROM** `{opacityVariable, opacityValue}` **TO** `{opacityVar, opacityVal}`.  You can think of these as **named parameters**, so you cannot change the names _(make sense)_?

At any rate, this does in fact work!

```js
const colorFn = (cssVar, {opacityVariable, opacityValue}) => {
  if (opacityValue !== undefined) {
    return `rgba(var(--${cssVar}), ${opacityValue})`
  }
  if (opacityVariable !== undefined) {
    return `rgba(var(--${cssVar}), var(${opacityVariable}, 1))`
  }
  return `rgb(var(--${cssVar}))`
};

module.exports = {
  theme: {
    extend: {
      colors: {
        "primary":   (params) => colorFn('color-primary',   params),
        "secondary": (params) => colorFn('color-secondary', params),
      }
    }
  }
}
```

**I still have a problem** where references to `tx-primary` **works** but `tx-primary-400` is being purged and dropped :-(  

Not sure what is going on _**Any ideas on this?**_

**Comment by jdf221** [comment]
@KevinAst unless I'm missing something from what you posted in order to use `tx-primary-400` you would need to define the `primary` colors as an object in your Tailwind config.

Like so:
```javascript
colors: {
  primary: {
    DEFAULT: (params) => colorFn("color-primary", params),
    400: (params) => colorFn("color-primary-400", params),
    500: (params) => colorFn("color-primary-500", params),
    etc: "etc...",
  },
}
```

Tailwind doesn't generate the color shades automatically. (And that DEFAULT property refers to using the `tx-primary` class without anything appended to it)

Also this is the helper function I ended up using so I wouldn't duplicate the rgba logic, personally I prefer it over having to manually pass the params for all my colors:

```javascript
function cssVarRgbHelper(cssVariable) {
  return ({ opacityVariable, opacityValue }) => {
    if (opacityValue !== undefined) {
      return `rgba(var(--${cssVariable}), ${opacityValue})`;
    }
    if (opacityVariable !== undefined) {
      return `rgba(var(--${cssVariable}), var(${opacityVariable}, 1))`;
    }
    return `rgb(var(--${cssVariable}))`;
  };
}

// Usage:
colors: {
  test: cssVarRgbHelper("my-custom-color")
}
```

**Comment by KevinAst** [comment]
@jdf221 thanks so much for your insight.

<br/>

**First, Regarding your helper function**:

I like your solution much better ... it is more "function oriented".

<br/>

**Second, Regarding tailwind shade generation**:

I was starting to come to the same understanding, but you confirmed it _(you can probably tell that I am a new tailwind user)_.  As a result, I am refining my approach to my utility.

Thanks for your mention of the **DEFAULT** usage semantics _(this will be useful in my new approach)_.  I did find mention of **DEFAULT** in the docs, however I have not found a reference to color definition through a function _(as you show in your example)_ ... **any insight on where you found this (docs/source)**?

Thanks again.

**Comment by jdf221** [comment]
@KevinAst 
> however I have not found a reference to color definition through a function (as you show in your example)

Bit confused on what you mean here. Your solution is also defining a color through a function. Your's and my code are actually very similar.

What you're doing here is actually a function:
```javascript
"primary": (params) => colorFn('color-primary', params),
```
Here it is expanded to what's actually going on:

```javascript
"primary": function(params) {
    return colorFn('color-primary',   params);
}
```

Mine is simply a function returning a function. So the parent function takes an argument of the css var name and the returned function can use that argument.

And about how the parameters work for the code provided in this repository:

(`{opacityVariable, opacityValue}`) is [destructuring an object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Basic_assignment:~:text=Basic%20assignment). Tailwind passes an object into the function that contains various properties, which include `opacityVariable` and `opacityValue`. The destructuring expression pulls properties out of the object and creates scope level variables of them. That's why when you renamed them it stopped working.

 I'm happy to explain what's going on with those named parameters in more detail if you want.

Sorry if I misunderstood what you were asking or if you already understood all the above :P

**Comment by KevinAst** [comment]
@jdf221, sorry for the confusion.

Yes - I fully understand your helper implementation.  It returns a function that has access to `cssVariable` via closure.

The key thing I learned from this thread (and you) is that tailwind does not generate color shades automatically.

What I failed to realize is that your example enumerating various color shades (`{ DEFAULT: fnRef, '400': fnRef ...}`) was using MY `colorFn` and is in fact the same API that is discussed in this repo.

I guess my question was related to this: It seems this API should be formally documented in the official tailwind docs, not just mentioned in a one-off repo.  I could not find this API in the formal docs :-(

- It could be that I missed this API in the formal docs.

- It could be that, the formal docs simply need to be updated to discuss this API.

- It could be that this API is considered to be internal.  However if that is the case, our production code should not rely on it.

Thoughts?

**Comment by jdf221** [comment]
Yeah I don't think the docs talk about this at all. Only reference is a link to this repository on the color customizing page.

Would definitely make sense to include a little section saying "yeah this exists" and talking about what params this function can get.

**Comment by mertasan** [comment]
This can make things easier. 🥳
 https://github.com/mertasan/tailwindcss-variables#colorvariable

**Comment by sanjade** [comment]
For color shades,

```
const colorFn = (color) => {
    return new Array(10)
      .fill(0)
      .map((_, i) => (i === 0 ? 50 : i * 100))
      .reduce((acc, curr) => {
        acc[curr] = (cssVar, { opacityVariable, opacityValue }) => {
            if (opacityValue !== undefined) {
            return `rgba(var(--${cssVar}), ${opacityValue})`;
            }
            if (opacityVariable !== undefined) {
            return `rgba(var(--${cssVar}), var(${opacityVariable}, 1))`;
            }
            return `rgb(var(--${cssVar}))`;
        }
        return acc;
      }, {});
}

module.exports = {
    theme: {
        colors: {
            primary: colorShadesFn("primary")
        }
    }
}
```

**Comment by tremby** [comment]
I did it like this:

```js
function colorVarWithOpacity(varName) {
  return function ({ opacityVariable, opacityValue }) {
    if (opacityValue != null) return `rgba(var(${varName}), ${opacityValue})`;
    if (opacityVariable != null) return `rgba(var(${varName}), var(${opacityVariable}, 1))`;
    return `rgb(var(${varName}))`;
  }
}
```

And then things like

```
colors: {
  brand: {
    100: colorVarWithOpacity("--color-brand-100"),
    300: colorVarWithOpacity("--color-brand-300"),
...
```

**Comment by tremby** [comment]
Oh my goodness just saw @mertasan's link above -- there's a built in function for it! I'll use that instead...
